query ($navigationUid: String!) {
  filterOptionList: filters(
    where: { navigations_filters: { navigation_uid: { _eq: $navigationUid } } }
  ) {
    uid
    name
    options: filter_options(
      where: { navigations_filter_options: { navigation_uid: { _eq: $navigationUid } } }
    ) {
      uid
      name
    }
  }
}
