query ($pageUrlPath: String!) {
  layouts: layouts(where: { page_url_path: { _eq: $pageUrlPath } }) {
    uid
    pageTitle: page_title
    detail
  }

  layoutItemList: layout_items(
    where: { layout: { page_url_path: { _eq: $pageUrlPath } } }
    order_by: { index: asc }
  ) {
    uid
    mode
    detail
    card: layout_card {
      uid
      detail
    }
  }
}
